name: Build Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/my-cloud-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-cloud-app:${{ github.sha }}

      - name: Deploy to Azure Container App
        run: |
          az containerapp update \
            --name DEINE_CONTAINER_APP:mo123 \
            --resource-group DEINE_RESOURCE_GROUP:ma123 \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/my-cloud-app:${{ github.sha }}
