name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker Image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/my-cloud-app:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/my-cloud-app:latest
